image: registry.gitlab.com/vyacheslav.vanin/vvv3d

before_script:
  - g++ -v
  - which g++
  - free -h

variables:
  GIT_SUBMODULE_STRATEGY: recursive 

rspec:
  script:
    - Xvfb :1 -screen 0 1920x1080x24+32 -fbdir /var/tmp &
    - export DISPLAY=:1
    - mkdir build
    - cd build
    - cmake .. -DWITH_TESTS=yes
    - make -j
    - ./tests/vvv3d_test
    - rm -rf *
    - cmake .. -DWITH_TESTS=yes -DVVV3D_BACKEND=Qt
    - make
    - ./tests/vvv3d_test
