before_script:
  - apt-get update -qq
  - apt-get install -y -qq
        libboost-system-dev cmake libgtest-dev
        libfreetype6-dev libjpeg-dev libgl-dev
        libsdl2-dev libfontconfig-dev libglew-dev xvfb
  - (cd /usr/src/gtest; cmake . && make -j8 && cp *.a /usr/lib/)
  - g++ -v
  - which g++

variables:
  GIT_SUBMODULE_STRATEGY: recursive 

rspec:
  script:
    - Xvfb :1 -screen 0 1920x1080x24+32 -fbdir /var/tmp &
    - export DISPLAY=:1
    - mkdir build
    - cd build
    - cmake ..
    - make -j
    - make test
