#pragma once
#include <vvv3d/vvv3d.hpp>
#include <vvv3d/std/gui/widgetindex/gui_layer.hpp>
#include <vvv3d/std/gui/widget.hpp>
#include <vvv3d/std/gui/panel.hpp>
#include <vvv3d/std/gui/textwidget.hpp>
#include <vvv3d/std/gui/imagewidget.hpp>
#include <vvv3d/std/gui/colorrectanglewidget.hpp>
#include <vvv3d/std/gui/buttontext.hpp>
#include <vvv3d/std/gui/lineedit.hpp>
#include <vvv3d/std/gui/horizontallayout.hpp>
#include <vvv3d/std/gui/verticallayout.hpp>
#include <vvv3d/std/gui/activewidget.hpp>
#include <vvv3d/std/gui/sliderbase.hpp>
#include <vvv3d/std/gui/hslider.hpp>
#include <vvv3d/std/gui/properties/itext.hpp>
#include <vvv3d/std/gui/properties/icolor.hpp>
#include <vvv3d/std/gui/properties/icontainer.hpp>
