#pragma once
#include <vvv3d/gui/properties/iaction.hpp>
#include <vvv3d/gui/properties/icolor.hpp>
#include <vvv3d/gui/properties/icontainer.hpp>
#include <vvv3d/gui/properties/itext.hpp>
#include <vvv3d/gui/widgetindex/gui_layer.hpp>
#include <vvv3d/gui/widgets/activewidget.hpp>
#include <vvv3d/gui/widgets/buttontext.hpp>
#include <vvv3d/gui/widgets/colorrectanglewidget.hpp>
#include <vvv3d/gui/widgets/imagewidget.hpp>
#include <vvv3d/gui/widgets/layouts/horizontallayout.hpp>
#include <vvv3d/gui/widgets/layouts/layout.hpp>
#include <vvv3d/gui/widgets/layouts/verticallayout.hpp>
#include <vvv3d/gui/widgets/lineedit.hpp>
#include <vvv3d/gui/widgets/panel.hpp>
#include <vvv3d/gui/widgets/sliderbase.hpp>
#include <vvv3d/gui/widgets/sliderh.hpp>
#include <vvv3d/gui/widgets/sliderv.hpp>
#include <vvv3d/gui/widgets/textwidget.hpp>
#include <vvv3d/gui/widgets/widget.hpp>
#include <vvv3d/vvv3d.hpp>
